---
title: "Week 1 Update"
author: "Rachel Donahue, Andrew Sistisky, Lauren Temple"
date: "4/4/2022"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(readxl, tidyverse, Rfssa, plotly, fda,
               cranly, ggplot2, vtable)

discrete <- read_excel("Data/discrete.xls")
IDinfo <- read_excel("Data/IDinfo.xls")
source(file="EDA_RD.R")
source(file= "Recreating_Plots.R")
```

## 
```{r echo=F}
#Number of trials
Kable(nrow(IDinfo))

#Number of Left and Right
IDinfo%>%group_by(KNEE)%>%summarize(count=n())

#Number of Participants that have trials
IDinfo%>%group_by(KNEE)%>%summarize(count=n_distinct(ID))
```

## V_GRF_stance_N plot
```{r echo=F}
ggplot(plot_V_GRF, aes(Time, value, group = V_GRF_stance, color = V_GRF_stance)) + 
  geom_line() +
  scale_colour_manual(values = mycolors) +
  theme(legend.position = "none")
```

## V_GRF_stance_N average plot
```{r}
# Plotting avg per time point
plot_V_GRF %>%
                      group_by(Time) %>%
                      summarise(avg_value = mean(value))
ggplot(avg_plot_V_GRF, aes(Time, avg_value)) + geom_line()
```

## ML_GRF_stance_N plot

```{r}
melt(ML_GRF_stance_N,  id.vars = 'Time', variable.name = 'ML_GRF_stance')
ggplot(plot_ML_GRF, aes(Time, value, group = ML_GRF_stance, color = ML_GRF_stance)) + 
  geom_line() +
  scale_colour_manual(values = mycolors) +
  theme(legend.position = "none")
```

## ML_GRF_stance_N average plot
```{r}
plot_ML_GRF %>%
  group_by(Time) %>%
  summarise(avg_value = mean(value))
ggplot(avg_plot_ML_GRF, aes(Time, avg_value)) + geom_line()
```

## AP_GRF_stance_N plot
```{r}
melt(AP_GRF_stance_N,  id.vars = 'Time', variable.name = 'AP_GRF_stance')
ggplot(plot_AP_GRF, aes(Time, value, group = AP_GRF_stance, color = AP_GRF_stance)) + 
  geom_line() +
  scale_colour_manual(values = mycolors) +
  theme(legend.position = "none")
```

## AP_GRF_stance_N average plot
```{r}
plot_AP_GRF %>%
  group_by(Time) %>%
  summarise(avg_value = mean(value))
ggplot(avg_plot_AP_GRF, aes(Time, avg_value)) + geom_line()
```


## Questions

- Is there an advantage to working with the non-time normalized files?
- Better ways to determine the outcome measures?
